version: '3.8'
services:
  app:
    build: .
    container_name: url-shortener-app
    restart: always
    ports:
      - "4444:4444"
    depends_on:
      - redis
    env_file:
      - .env  
    environment:
      - REDIS_HOST=url-shortener-redis  # 👈 Set Redis host in ENV
    networks:
      - app-network  # 👈 Use a shared network

  redis:
    image: redis:latest
    container_name: url-shortener-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network  # 👈 Use the same network

networks:
  app-network:  # 👈 Define the shared network
    driver: bridge

volumes:
  mongo_data:
