version: '3.8'
services:
  app:
    build: .
    container_name: url-shortener-app
    restart: always
    ports:
      - "4444:4444"
    depends_on:
      - redis
    env_file:
      - .env  

  redis:
    image: redis:latest
    container_name: url-shortener-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data: